name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Mamba
      uses: conda-incubator/setup-mamba@v5

    - name: Create conda environment
      run: |
        wget https://data.qiime2.org/distro/core/qiime2-2023.2-py38-linux-conda.yml
        mamba env create -n test --file qiime2-2023.2-py38-linux-conda.yml
        conda activate test
        mamba install -y -c conda-forge -c bioconda r-spieceasi flake8

    - name: Install Python package
      run: |
        conda activate test
        pip install .

    - name: Run Flake8
      run: |
        conda activate test
        flake8

    - name: Run pytest
      run: |
        conda activate test
        pytest
